# Form implementation generated from reading ui file 'create_account.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1288, 653)
        Dialog.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(410, 40, 551, 571))
        self.widget.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(110, 40, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(37)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 130, 121, 275))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(280, 140, 201, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 20)
        self.verticalLayout_2.setSpacing(45)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout_2.addWidget(self.name)
        self.userline = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.userline.setFont(font)
        self.userline.setObjectName("userline")
        self.verticalLayout_2.addWidget(self.userline)
        self.pass_line = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pass_line.setFont(font)
        self.pass_line.setObjectName("pass_line")
        self.pass_line.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)  # Set to password mode
        self.verticalLayout_2.addWidget(self.pass_line)
        self.chline = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.chline.setFont(font)
        self.chline.setObjectName("chline")
        self.chline.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)  # Set to password mode
        self.verticalLayout_2.addWidget(self.chline)
        self.ok = QtWidgets.QDialogButtonBox(parent=self.widget)
        self.ok.setGeometry(QtCore.QRect(180, 500, 341, 32))
        self.ok.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ok.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ok.setObjectName("ok")
        self.show_pass = QtWidgets.QCheckBox(parent=self.widget)
        self.show_pass.setGeometry(QtCore.QRect(200, 450, 119, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_pass.setFont(font)
        self.show_pass.setStyleSheet("color: rgb(27, 39, 118);")
        self.show_pass.setObjectName("show_pass")

        self.retranslateUi(Dialog)
        self.ok.accepted.connect(Dialog.accept) # type: ignore
        self.ok.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-style:italic; color:#1b2776;\">Create an Account</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-style:italic;\">Name</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#1b2776;\">Username</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">P</span><span style=\" font-size:11pt; color:#1b2776;\">assword</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Check Password</span></p></body></html>"))
        self.show_pass.setText(_translate("Dialog", "Show Password"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
