# Form implementation generated from reading ui file 'report_history4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1288, 653)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1288, 41))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(33, 48, 145, 255), stop:1 rgba(243, 243, 243, 255));\n"
"\n"
"border:none")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 40, 1211, 571))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"background-color: rgb(247, 247, 247);")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 70, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(22)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 420, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(22)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(60, 220, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(22)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(60, 140, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(22)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(270, 480, 521, 121))
        self.textBrowser.setObjectName("textBrowser")
        self.dashboard = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dashboard.setGeometry(QtCore.QRect(0, -18, 151, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        self.dashboard.setFont(font)
        self.dashboard.setStyleSheet("background:none;\n"
"border:none")
        self.dashboard.setObjectName("dashboard")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(280, -30, 631, 201))
        self.label_10.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("C:/Users/Hp/OneDrive/Desktop/images for hms/logo-removebg-preview.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_27 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(60, 380, 201, 72))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(910, 400, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(910, 360, 116, 35))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(22)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(60, 360, 204, 45))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(22)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"color: rgb(0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 320, 71, 45))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(950, 310, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(820, 310, 131, 45))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_25 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(130, 320, 51, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_25.setObjectName("label_25")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(400, 330, 308, 45))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_26 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(460, 330, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_26.setObjectName("label_26")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(60, 190, 111, 43))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_16.setObjectName("label_16")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(810, 180, 131, 43))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(950, 180, 100, 43))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(180, 180, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_19.setObjectName("label_19")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(820, 270, 126, 43))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_21 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(950, 270, 138, 43))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 270, 48, 43))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(470, 270, 102, 43))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 270, 54, 43))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_24 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(120, 270, 121, 43))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("\n"
"background:none;\n"
"border:none;\n"
"")
        self.label_24.setObjectName("label_24")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1288, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#1b2776;\">Medical Report</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Notes"))
        self.label_13.setText(_translate("MainWindow", "Patient Information"))
        self.label_17.setText(_translate("MainWindow", "Visit Information "))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Patient diagnosed with hypertension</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\"> and treated using beta-blockers</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\"> and ACE inhibitors.</span></p></body></html>"))
        self.dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>Beta-blockers, ACE inhibitors</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>Hypertension</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Diagnosis"))
        self.label_14.setText(_translate("MainWindow", "Treatment"))
        self.label_12.setText(_translate("MainWindow", "Gender :"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p>Rs.18352</p></td></tr></table></td></tr></table></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Billing Amount :"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p>Male</p></td></tr></table></td></tr></table></body></html>"))
        self.label_7.setText(_translate("MainWindow", "CNIC :"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p>16102-1980230-3</p></td></tr></table></td></tr></table></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Doctor Name  :"))
        self.label_6.setText(_translate("MainWindow", "Admission Date :"))
        self.label_23.setText(_translate("MainWindow", "2023-10-28"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Dr. Nadia</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Discharge  Date :"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>2023-04-05</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Age :"))
        self.label_22.setText(_translate("MainWindow", "26"))
        self.label_11.setText(_translate("MainWindow", "Name :"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>Imran Tariq</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
